#index:
#  path: /
#  controller: App\Controller\LuckyController::number
# config/routes.yaml

# the "app_lucky_number" route name is not important yet
#app_lucky_number:
###  path: /lucky/number
###  controller: App\Controller\LuckyController::number

#create_product:
#  path: /product
#  controller: App\Controller\ProductController::createProduct()